[workspace]
members = ["backend", "frontend"]
default-members = ["backend"]
resolver = "2"

[profile.dev]
incremental = true

[profile.dev.package.backtrace]
opt-level = 3

[profile.dev.package.sqlx-macros]
opt-level = 3
