services:
  nginx:
    image: nginx:latest
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - ./.conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    user: user
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      tile-server:
        condition: service_healthy

  tile-server:
    image: overv/openstreetmap-tile-server
    volumes:
      - osm-data:/data/database/
      - osm-tiles:/data/tiles/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: "run"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 30s

  tile-import:
    image: overv/openstreetmap-tile-server
    volumes:
      - ./regions/northern-zone-latest.osm.pbf:/data/region.osm.pbf
      - osm-data:/data/database/
    command: "import"
    profiles:
      - "import"
  
  import:
    image: busybox
    profiles: ["import"]
    depends_on:
      tile-import:
        condition: service_completed_successfully

volumes:
  osm-data:
    external: true
  osm-tiles:
    external: true
