services:
  workspace:
    build: .
    volumes:
      - ..:/workspace:cached
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    user: user

  tile-server:
    image: overv/openstreetmap-tile-server
    volumes:
      - osm-data:/data/database/
      - osm-tiles:/data/tiles/
    ports:
      - "5432:5432"
      - "8000:80"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: "run"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 30s
  
volumes:
  osm-data:
    external: true
  osm-tiles:
    external: true
